<?php

namespace Unicart\Langs;

// Hindi translation
return [
    'invalid_validator' => 'वैलिडेशन के लिए अमान्य वैलिडेटर',
    'unicart_exceptions' => [
        'empty_cart' => 'कार्ट खाली है',
        'float_item_id_not_allowed' => 'फ्लोट मानों को आइटम आईडी के रूप में अनुमति नहीं है। आईडी: :id।',
        'invalid_item_price' => 'आईडी: :id वाले आइटम की कीमत 0 या उससे कम नहीं हो सकती।',
        'invalid_item_qty' => 'आईडी: :id वाले आइटम की मात्रा 0 या उससे कम नहीं हो सकती।',
        'item_exist' => 'आईडी: :id वाला आइटम पहले से मौजूद है।',
        'item_doesnt_exist' => 'आईडी: :id वाला आइटम मौजूद नहीं है।',
        'invalid_item_upto_amount' => 'आईडी: :id वाले आइटम के लिए अपटू डिस्काउंट राशि अमान्य है।',
        'cannt_apply_on_cart_due_to_item' => 'कार्ट पर :applying लागू नहीं किया जा सकता क्योंकि टैक्स पहले ही आइटम आईडी: :id पर लागू हो चुका है।',
        'cannt_add_in_cart_due_to_item' => 'कार्ट शुरू होने के बाद आईडी: :id वाले आइटम पर :applying नहीं जोड़ा जा सकता।',
        'invalid_cart_upto_amount' => 'कार्ट के लिए अपटू डिस्काउंट राशि अमान्य है।',
        'cannt_add_discount_after_tax' => 'टैक्स लगने के बाद डिस्काउंट नहीं जोड़ा जा सकता।',
        'cannt_add_discount_after_delivery' => 'डिलीवरी चार्ज जोड़ने के बाद डिस्काउंट नहीं जोड़ा जा सकता।',
        'cannt_add_another_delivery' => 'कार्ट पर एक और डिलीवरी चार्ज नहीं जोड़ा जा सकता।',
        'invalid_buy_get_qty_for_item' => 'आईडी: :id वाले आइटम के लिए खरीद या प्राप्त मात्रा 0 या उससे कम नहीं हो सकती।',
        'invalid_qty_for_item_bxgy' => 'आईडी: :id वाले आइटम के लिए निर्दिष्ट BxGy मानों के लिए मात्रा अपर्याप्त है।',
        'cannt_apply_sxgy' => 'कार्ट पर एक और SxGy डिस्काउंट लागू नहीं किया जा सकता।',
        'invalid_sxgy' => 'SpendXgetY डिस्काउंट के लिए खर्च या प्राप्त 0 या उससे कम नहीं हो सकते।',
        'invalid_spend_in_sxgy' => 'SpendXgetY डिस्काउंट के लिए खर्च प्राप्त से कम नहीं हो सकता।',
        'discount_stacking_disabled' => 'डिस्काउंट स्टैकिंग अक्षम है। पहले से ही एक डिस्काउंट लागू किया गया है।',
        'invalid_discount_percentage_for_item' => 'आईडी: :id वाले आइटम के लिए डिस्काउंट प्रतिशत 0 या उससे कम नहीं हो सकता।',
        'invalid_discount_percentage' => 'डिस्काउंट प्रतिशत 0 या उससे कम नहीं हो सकता।',
        'invalid_discount_for_item' => 'आईडी: :id वाले आइटम के लिए डिस्काउंट 0 या उससे कम नहीं हो सकता।',
        'invalid_discount' => 'डिस्काउंट 0 या उससे कम नहीं हो सकता।',
        'invalid_delivery_charge_for_item' => 'आईडी: :id वाले आइटम के लिए डिलीवरी चार्ज 0 या उससे कम नहीं हो सकता।',
        'invalid_delivery_charge' => 'डिलीवरी चार्ज 0 या उससे कम नहीं हो सकता।',
        'invalid_tax_for_item' => 'आईडी: :id वाले आइटम के लिए टैक्स 0 या उससे कम नहीं हो सकता।',
        'invalid_tax' => 'टैक्स 0 या उससे कम नहीं हो सकता।',
    ],
    'item_exceptions' => [
        'invalid_id' => 'फ्लोट मानों को आइटम आईडी के रूप में अनुमति नहीं है। आईडी: :id।',
        'invalid_price' => 'आईडी: :id वाले आइटम की कीमत 0 या उससे कम नहीं हो सकती।',
        'invalid_qty' => 'आईडी: :id वाले आइटम की मात्रा 0 या उससे कम नहीं हो सकती।',
        'invalid_upto_amount' => 'आईडी: :id वाले आइटम के लिए अपटू डिस्काउंट राशि अमान्य है।',
        'cannt_add_discount_after_tax' => 'आईडी: :id वाले आइटम पर टैक्स लगने के बाद डिस्काउंट नहीं जोड़ा जा सकता।',
        'cannt_add_discount_after_delivery_charge' => 'आईडी: :id वाले आइटम पर डिलीवरी चार्ज जोड़ने के बाद डिस्काउंट नहीं जोड़ा जा सकता।',
        'cannt_add_delivery_charge' => 'आईडी: :id वाले आइटम पर एक और डिलीवरी चार्ज नहीं जोड़ा जा सकता।',
        'cannt_add_bxgy_after_bxgy' => 'आईडी: :id वाले आइटम पर BxGy जोड़ने के बाद एक और BxGy नहीं जोड़ा जा सकता।',
        'cannt_add_bxgy_after_dicount' => 'आईडी: :id वाले आइटम पर अन्य डिस्काउंट जोड़ने के बाद BxGy नहीं जोड़ा जा सकता।',
        'cannt_add_discount_after_bxgy' => 'आईडी: :id वाले आइटम पर BxGy जोड़ने के बाद डिस्काउंट नहीं जोड़ा जा सकता।',
        'invalid_bxgy_qty' => 'आईडी: :id वाले आइटम के लिए BxGy की खरीद या प्राप्त मात्रा नकारात्मक नहीं हो सकती।',
        'dissatified_bxgy_qty' => 'आईडी: :id वाले आइटम के लिए BxGy की खरीद और प्राप्त मात्रा संतोषजनक नहीं है।',
        'discount_stacking_disabled' => 'डिस्काउंट स्टैकिंग अक्षम है। इस आइटम पर पहले से ही डिस्काउंट लागू है।',
        'invalid_discount_percentage' => 'आईडी: :id वाले आइटम के लिए डिस्काउंट प्रतिशत 0 या उससे कम नहीं हो सकता।',
        'invalid_discount' => 'आईडी: :id वाले आइटम के लिए डिस्काउंट 0 या उससे कम नहीं हो सकता।',
        'invalid_delivery_charge' => 'आईडी: :id वाले आइटम के लिए डिलीवरी चार्ज 0 या उससे कम नहीं हो सकता।',
        'invalid_tax' => 'आईडी: :id वाले आइटम के लिए टैक्स 0 या उससे कम नहीं हो सकता।'
    ],
    'invoice' => [
        'title' => 'चालान',
        'logo' => 'लोगो',
        'order' => 'आदेश',
        'date' => 'तारीख',
        'bill_from' => 'बिल भेजने वाला',
        'bill_to' => 'बिल प्राप्तकर्ता',
        'cart' => 'कार्ट',
        'cart_applicables' => 'कार्ट स्तर पर लागू',
        'item' => 'आइटम',
        'qty' => 'मात्रा',
        'price' => 'कीमत',
        'discount' => 'छूट',
        'delivery_charge' => 'वितरण शुल्क',
        'tax' => 'कर',
        'total' => 'कुल',
        'total_discount' => 'कुल छूट',
        'total_delivery' => 'कुल वितरण',
        'total_tax' => 'कुल कर'
    ]
];
